language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "nightly"
# command to install dependencies


language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install: "pip install -r requirements.txt"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
notifications: 
  email: false
# command to run tests
# script: nosetests
