name: pisces-dev
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- obspy>=1.4.1
- sqlalchemy>1.4
- click
- oracle-instant-client
- cx_oracle
- ipython
- black
- make
- myst-parser
- pydata-sphinx-theme
- sphinx >= 5.0
- sphinx-book-theme
- sphinx-click
- numpydoc
- pytest
- pip
- pip:
  - -e .[e1]
