site_name: Pisces
site_url: http://www.jkmacc-LANL.github.io/pisces
site_description: A practical seismological database library in Python.

pages:
- ['index.md', 'Introduction']
- ['database/css-tables.md', 'Database', 'CSS 3.0 Core Tables']
- ['database/keys.md', 'Database', 'Primary and Unique Keys']
- ['querying/queries-joins.md', 'Querying', 'Queries and Joins']
- ['querying/geographic-queries.md', 'Querying', 'Geographic Queries']
- ['io/data.md', 'Data I/O', 'Import/Export Data']
- ['io/flatfiles.md', 'Data I/O', 'Import/Export Flat Files']
- ['roadmap.md', 'Development Roadmap']
- ['api/index.md', 'API Documentation', 'Pisces API']
- ['_build/html/index.html', 'API Documentation', 'Pisces API']

theme_dir: 'theme'
