CC=gcc
CCFLAGS=-Wall -fPIC -shared -dynamiclib -lm -I. -arch i386 -arch x86_64 -g

all:	libecompression.dylib 

clean:
		rm libecompression.dylib

libecompression.dylib:	e_compression.c 
		$(CC) $(CCFLAGS) e_compression.c -o libecompression.dylib

install:
		cp libecompression.dylib ../../lib/libecompression.dylib
