site_name: Pisces
site_url: http://www.jkmacc-LANL.github.io/pisces
site_description: A practical seismological database library in Python.

repo_url: https://github.com/jkmacc-lanl/pisces

pages:
- Home: 'index.md'
- Tutorial:
    - 'Database Tables': 'tutorial.tables.md'
    - 'Using the Database': 'tutorial.queries.md'
    - 'Import/Export Waveforms': 'tutorial.waveforms.md'
    - 'Import/Export Flat Files': 'tutorial.flatfiles.md'
- API Documentation: 'api.md'
- About:
    - 'Roadmap': 'about.roadmap.md'
    - 'License': 'about.license.md'
    - "User's Group": 'about.group.md'

docs_dir: 'source/pages'
site_dir: 'html'
theme: 'readthedocs'
# theme_center_lead: true
