name: Sphinx docs to GitHub Pages

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          environment-file: ../environment-dev.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build the docs
        shell: bash -l {0}
        run: |
          cd docs
          make clean 
          make apidocs && make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }} # must be publishing master/main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html